# Generated by Django 4.2.5 on 2023-10-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appentrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Curses',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Students',
        ),
    ]
